const obj = [threeElement = {
	nameLiq: 'Three elements',
	img: 'images/bos1.png',
	skyColor: '#c51f3c',
	transToColor: '0px -13px 18px 2px rgba(197, 31, 60)',
	bgColor: 'linear-gradient(#fc9d0b, red)',
	music: '',
	maingBg: 'img/bgyellow.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/starsy.png',
	description: 'Очаровательный танец трёх фруктов, заставит вас войти в кураж и почувствовать баланс банана, клубники и драгонфрута. Как хороший фит, вы сможете наблюдать коллаборацию этих элементов, на прощание вы возьмите з собой ксило-сладкое вкус',
	colorText: '#FFFF00',
	colorBorder: '10px solid #FFFF00',
	colorBut: '#FFFF00',
	miniTitle: 'Три фрукта',
	bt: '1px solid #FFFF00'
},
wildHit = {
	nameLiq: 'Wild Hit',
	img: 'images/bos2.png',
	skyColor: '#1c0522',
	transToColor: '0px -13px 18px 2px rgba(28, 5, 34)',
	bgColor: 'linear-gradient(#2b1055, #7597de)',
	music: '',
	maingBg: 'img/mountains_front.png',
	secondBg: 'img/mountains_behind.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Этот Холодный, яркий и сладкий вкус, даст возможность поучуствовать истинную дикость лесных ягод.Наслаждйтесь чательно и внимательно, никто не знает в какой миг они могут резко изменить свой вкус',
	colorText: 'white',
	colorBorder: '10px solid white',
	colorBut: 'teal',
	miniTitle: 'Дикие ягоды',
	bt: '1px solid white'
},
vanillaWest = {
	nameLiq: 'Vanilla West',
	img: 'images/bos3.png',
	skyColor: '#fddc97',
	transToColor: '0px -13px 18px 2px rgba(253, 220, 151)',
	bgColor: 'linear-gradient(#fddc97, #2e1101)',
	music: '',
	maingBg: 'img/bgvanilla.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Этот вариант подойдёт для истинных ценителей настоящего табачного листа. Дикий запад, деревня, тлеют поля табака. На выдохе Вы почувствуете нотки ванильного морожена. Идеальный выбор для сопровождения захода солнца',
	colorText: 'black',
	colorBorder: '10px solid black',
	colorBut: 'black',
	miniTitle: 'Ванильный табак',
	bt: '1px solid black'
},
strawCake = {
	nameLiq: 'Straw Cake',
	img: 'images/bos4.png',
	skyColor: '#52acea',
	transToColor: '0px -13px 18px 2px rgba(82, 172, 234)',
	bgColor: 'linear-gradient(#52acea, red)',
	music: '',
	maingBg: 'img/bgcake.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Идеальный рецепт вкусного американского чизкейка. Мы долго работали над этим вкусом, чтоб Вы смогли попробовать эту кремовую выпечку. Творожный чизкейк с клубничным коктейлем, залитый на любой цвет кремами.',
	colorText: '#FF0033',
	colorBorder: '10px solid #FF0033',
	colorBut: '#FF0033',
	miniTitle: 'Клубничный чизкейк',
	bt: '1px solid #FF0033'
},
donutBoom = {
	nameLiq: 'Donut Boom',
	img: 'images/bos5.png',
	skyColor: '#9ed8eb',
	transToColor: '0px -13px 18px 2px rgba(167,222,226,1)',
	bgColor: 'linear-gradient(#9ed8eb, red)',
	music: '',
	maingBg: 'img/bgdonut.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'А что насчёт пончика? Нет, не просто пончика! С первого ж момента вы коснитесь класики. Она проберёт вас до глубинки, заставляет чётко увидеть глазурь с малиновой ноткой. Идеальной выбор то, кто предпочитает класику!',
	colorText: '#FF0033',
	colorBorder: '10px solid FF0033',
	colorBut: '#FF0033',
	miniTitle: 'Глазированный пончик',
	bt: '1px solid #FF0033'
},
peachGreen = {
	nameLiq: 'Peach & Green',
	img: 'images/bos6.png',
	skyColor: '#51cc47',
	transToColor: '0px -13px 18px 2px rgba(81, 204, 71)',
	bgColor: 'linear-gradient(#51cc47, orange)',
	music: '',
	maingBg: 'img/bggreen.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Если вы ценитель просты вкусов, то следующий вариант как раз Вам. Простой но свежий микс яблока и персика. Фрукты всегда могут разукрасить ваш день яркими красками. А ещё лучше утомить жажду. Холодок на выдохе всегда взбодрит вас в жаркие деньки',
	colorText: '#FF6600',
	colorBorder: '10px solid #FF6600',
	colorBut: '#FF6600',
	miniTitle: 'Персик & Яблоко',
	bt: '1px solid #FF6600'
},
coctail = {
	nameLiq: 'Yellow coctail',
	img: 'images/bos7.png',
	skyColor: '#387ec9',
	transToColor: '0px -13px 18px 2px rgba(56, 126, 201)',
	bgColor: 'linear-gradient(#387ec9, lightblue)',
	music: '',
	maingBg: 'img/bgcoctail.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Лето, время попробовать что-то вкусное, что приносит на природа. Что то молочное? Или же фрукты? А может всё вместе? Коктейль из летних фруктов. Дыня, банан, груша, и конечно же - нотки клубники.',
	colorText: '#FFFF33',
	colorBorder: '10px solid #FFFF33',
	colorBut: '#FFFF33',
	miniTitle: 'Желтый коктейль',
	bt: '1px solid #FFFF33'
},
granat = {
	nameLiq: 'granat',
	img: 'images/bos8.png',
	skyColor: '#387ec9',
	transToColor: 'linear-gradient(to top, #1c0522, transparent)',
	bgColor: 'linear-gradient(#387ec9, lightblue)',
	music: '',
	maingBg: 'img/bgcoctail.png',
	secondBg: 'img/empty.png',
	moonLogo: 'img/moon.png',
	star: 'img/stars.png',
	description: 'Что на счёт экзотики? Фрукты и дикие ягоды, то что нужно! Налитый солнцем гранат переполнить ваши вкусовые рецепторы, а на послевкусие припадает дикая черника? Хммм..',
	colorText: '#7597de',
	colorBorder: '10px solid #7597de',
	colorBut: '#7597de',
	miniTitle: 'Гранат & Черника',
	bt: '1px solid #7597de'
}];